# This file defines the contenttypes on the website. See the documentation for
# details: http://docs.bolt.cm/content#defining-contenttypes


# Entries can be used for things like 'news' or 'blogpostings'. They have a 'teaser',
# which can be used for a short blurb on listing-pages, allowing visitors to
# click-through to the rest of the entry. It also has fields for an image and an
# optional video.
# A relation is defined to the pages contenttype. This way you can refer to a page
# from your news-item.
# This contenttype defines 'categories' and 'tags' as taxonomies, allowing the
# editor to use both to categorize a specifig entry.
# The 'sort' is set to "datepublish DESC", which means that newer entries will
# show above older entries.

managers:
    name: Managers
    singular_name: Manager
    fields:
        name:
            type: text
        photo:
            type: image
        fonction:
            type: text
            class: large
        text_fr:
            type: html
        text_en:
            type: html
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    sort: datepublish DESC
    recordsperpage: 10

références:
    name: Références
    singular_name: Référence
    fields:
        name:
            type: text
        photo:
            type: image
        text_fr:
            type: html
        text_en:
            type: html
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    sort: datepublish DESC
    recordsperpage: 10

partenaires:
    name: Partenaires
    singular_name: Partenaire
    fields:
        name:
            type: text
        photo:
            type: image
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    sort: datepublish DESC
    recordsperpage: 10

# possible field types:
# text - varchar(256) - input type text.
# integer - integer - Input field for integer numbers.
# float - double - Input field for floating numbers, stored as 'Double'.
# geolocation - text (65kb) - Input field for geolocation. Enter an address, and the location is geocoded to latitude/longitude coordinates
# imagelist - text (65kb) - Input type for imagelists. Add multiple images with a description. Useful for image sliders, galleries, etcetera.
# image - varchar(256) - image select/upload widget, stored as filename.
# file - varchar(256) - file select/upload widget, stored as filename.
# video - varchar(256) - Video embed widget, stored as filename.
# html - text (65kb) - wysiwyg element.
# textarea - varchar(32768) - Simple, plain < textarea > field.
# datetime - datetime - date and time selector widget.
# date - datetime - date selector widget.
# select - varchar(256) - select with predefined values
# templateselect - varchar(256) - select with template filenames


# number (deprecated) - input type decimal(18,9), useful for storing number that need to be sortable
