# This is the config file for the Simple Forms extension.

template: _form.twig
mail_template: mail.twig
message_ok: Thanks! Your message has been sent.
message_error: There was an error in the form. Please check the form, and try again.
message_technical: There were some technical difficulties, so your message was not sent. We apologize for the inconvenience.
button_text: Ok

# A simple contact form. Use as {{ simpleform('contact') }} in your templates.
contact_fr:
  recipient_email: info@cfsaffinity.com
  recipient_name: Contact depuis site CFSA.
  fields:
    civilite:
      type: choice
      label: Civilité
      choices: [ '', Mlle, Mme, M ]
      required: true
    nom:
      type: text
      label: Nom
      required: true
    prenom:
      type: text
      label: Prénom
    email:
      type: email
      label: Email
      required: true
    fonction:
      type: text
      label: Fonction
      required: true
    societe:
      type: text
      label: Sociéte
      required: true
    activite:
      type: text
      label: Activité
    adresse:
      type: text
      label: Adresse
    cp:
      type: text
      label: Code postal
    telephone:
      type: text
      label: Téléphone
      required: true
    message:
      type: textarea
      required: true
      label: Vore message
      
      
contact_en:
  recipient_email: info@cfsaffinity.com
  recipient_name: Contact from CFSA website.
  fields:
    civilite:
      type: choice
      label: Greeting
      choices: [ '', Mlle, Mme, M ]
      required: true
    nom:
      type: text
      label: Surname
      required: true
    prenom:
      type: text
      label: First name
    email:
      type: email
      label: E-mail address
      required: true
    fonction:
      type: text
      label: Job title
      required: true
    societe:
      type: text
      label: Company name
      required: true
    activite:
      type: text
      label: Activity
    adresse:
      type: text
      label: Address
    cp:
      type: text
      label: Postal code
    telephone:
      type: text
      label: Telephone
      required: true
    message:
      type: textarea
      required: true
      label: Your message

# A demo form to showcase various options for fields. Use as
# {{ simpleform('demo') }} in your templates.
demo:
  recipient_email: info@example.org
  recipient_name: Info
  fields:
    subject:
      type: text
      class: wide
      required: false
      label: Subject of your message
      placeholder: Just a quick message ..
    name:
      type: text
      required: true
      placeholder: Your name ..
    email:
      type: email
      label: Email address
      required: true
      placeholder: Your email ..
    message:
      type: textarea
      required: true
      placeholder: Well, the other day I was thinking that maybe you ought to improve your website by adding ..
    favorite:
      type: choice
      label: My favorite animals are
      choices: [ Kittens, Puppies, Penguins, Koala bears, "I don't like animals" ]
      required: true
    option1:
      type: checkbox
      label: Newsletter
      placeholder: Yes, I <em>love</em> receiving <del>spam</del>, eh, newsletters.
    option2:
      type: checkbox
      label: Agree to this!
      placeholder: Yes, I will gladly agree to something or other.
      required: true
  button_text: Send the Demo form!


